# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DIDSR main page
email: cdrh-osel-didsr@fda.hhs.gov
description: >- # this means to ignore newlines until "baseurl:"
  DIDSR is the best!
baseurl: "/didsr.io" # the subpath of your site, e.g. /blog
url: "https://malago86.github.io" # the base hostname & protocol for your site
twitter_username: aldo_badano
github_username:  DIDSR
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown

# theme: jekyll-theme-tactile
titlecase: true
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
permalink: /:categories/:title/
paginate: 5 # amount of posts to show

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache